/**
 * @file PlaybackSession.h
 * @brief Defines the engine responsible for managing and traversing algorithm history.
 *
 * This file implements the consumer side of the Memento pattern. It takes the 
 * chronological history generated by an algorithm and provides VCR-like controls 
 * (play, pause, step) for the UI to iterate through the states at a human-readable pace.
 */

#ifndef ALGORITHM_VISUALIZER_PLAYBACK_PLAYBACK_SESSION_H
#define ALGORITHM_VISUALIZER_PLAYBACK_PLAYBACK_SESSION_H

#include "Algorithm/Algorithm.h"

#include <cstddef>
#include <stdexcept>
#include <vector>

namespace av::playback {

/**
 * @class PlaybackSession
 * @brief Manages the timeline and state of a visualized algorithm execution.
 *
 * The PlaybackSession acts as a timeline manager for PlaybackFrames (Mementos). 
 * It completely decouples the computational speed of the algorithm from the 
 * visual rendering speed of the UI, allowing users to step forward, step backward, 
 * or automatically advance through the algorithm's history safely.
 */
class PlaybackSession {
  public:
    /**
     * @brief Constructs an empty playback session.
     */
    PlaybackSession() = default;

    /**
     * @brief Constructs a session and pre-loads it with a sequence of frames.
     * @param frames The chronological history of states generated by an algorithm.
     */
    explicit PlaybackSession(std::vector<algorithm::PlaybackFrame> frames);

    /**
     * @brief Checks if the session currently holds any frames.
     * @return true If the timeline is empty.
     */
    [[nodiscard]] bool empty() const noexcept;

    /**
     * @brief Retrieves the total number of frames in the timeline.
     * @return std::size_t The frame count.
     */
    [[nodiscard]] std::size_t frameCount() const noexcept;

    /**
     * @brief Retrieves the current position of the playhead.
     * @return std::size_t The index of the currently active frame.
     */
    [[nodiscard]] std::size_t currentIndex() const noexcept;

    /**
     * @brief Checks if automatic playback is currently paused.
     * @return true If the session requires manual stepping or resumption.
     */
    [[nodiscard]] bool isPaused() const noexcept;

    /**
     * @brief Checks if the playhead has reached the final frame of the timeline.
     * @return true If the simulation is complete.
     */
    [[nodiscard]] bool isFinished() const noexcept;

    /**
     * @brief Retrieves the active frame at the current playhead position.
     * * @throws PlaybackError If the session is empty and a frame is requested.
     * @return const algorithm::PlaybackFrame& An immutable reference to the current state snapshot.
     */
    [[nodiscard]] const algorithm::PlaybackFrame& currentFrame() const;

    /**
     * @brief Overwrites the current timeline with a new sequence of frames and resets the playhead.
     * @param frames The new chronological history of states to visualize.
     */
    void load(std::vector<algorithm::PlaybackFrame> frames);

    /**
     * @brief Halts automatic progression of the timeline.
     */
    void pause() noexcept;

    /**
     * @brief Flags the timeline to automatically progress on subsequent ticks.
     */
    void resume() noexcept;

    /**
     * @brief Rewinds the playhead to the very first frame and pauses execution.
     */
    void reset() noexcept;

    /**
     * @brief Manually advances the playhead by one frame.
     * @return true If the step was successful (i.e., not already at the end).
     */
    bool stepForward() noexcept;

    /**
     * @brief Manually rewinds the playhead by one frame.
     * @return true If the step was successful (i.e., not already at the beginning).
     */
    bool stepBackward() noexcept;

    /**
     * @brief Advances the timeline if the session is not paused and not finished.
     * * Typically called once per frame by the application's main render loop.
     * @return true If the playhead moved forward during this tick.
     */
    bool advanceTick() noexcept;

  private:
    std::vector<algorithm::PlaybackFrame> frames_ {};  /**< The internal timeline of Mementos. */
    std::size_t currentIndex_ {0};                     /**< The current position of the playhead. */
    bool paused_ {true};                               /**< The active execution state. */
};

/**
 * @class PlaybackError
 * @brief Custom exception thrown when illegal playback operations occur (e.g., requesting a frame from an empty session).
 */
class PlaybackError : public std::runtime_error {
  public:
    using std::runtime_error::runtime_error;
};

}  // namespace av::playback

#endif